baseURL = "https://coopcycle.org/"
title = "CoopCycle"
theme = "coopcycle"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[Languages]
[Languages.en]
title = "My blog"

[Languages.fr]
title = "Mon blog"
