baseURL = "https://coopcycle.org/"
theme = "coopcycle"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[Languages]
[Languages.en]
title = "CoopCycle - Open source delivery platform. Only for worker-owned business."

[Languages.fr]
title = "CoopCycle - Plateforme de livraison open source. Seulement pour les coopératives."
