baseURL = "https://coopcycle.org/"
theme = "coopcycle"

DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[Taxonomies]

[Languages]

[Languages.en]
title = "CoopCycle - Open source delivery platform. Only for worker-owned business."

# [[Languages.en.menu.main]]
# name = "Demo"
# weight = 4
# identifier = "Demo"
# url = "https://demo.coopcycle.org"

[Languages.fr]
title = "CoopCycle - Plateforme de livraison open source. Seulement pour les coopératives."

# [[Languages.fr.menu.main]]
# name = "Démo"
# weight = 4
# i# dentifier = "Demo"
# url = "https://demo.coopcycle.org"

[Languages.fr.Taxonomies]

