baseURL = "https://coopcycle.org/"
theme = "coopcycle"

DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[blackfriday]
extensions = ["hardLineBreak"]

[Taxonomies]

[Languages]

### English

[Languages.en]
title = "CoopCycle - Open source logistics platform software. Only for worker-owned business."
description = "CoopCycle is an open source software for running a logistics platform."

### French

[Languages.fr]
title = "CoopCycle - Logiciel de plateforme logistique open source. Seulement pour les coopératives."
description = "CoopCycle est un logiciel open source permettant de gérer une plateforme logistique."

[[Languages.fr.menu.main]]
name = "Blog"
weight = 4
identifier = "blog"
url = "https://blogs.mediapart.fr/coopcycle"

### Spanish

[Languages.es]
title = "CoopCycle - Software open source de plataforma logística. Solo para cooperativas."
description = "CoopCycle es un software open source para administrar una plataforma logística."
