# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "CoopCycle"
homepage = "https://coopcycle.org/"
tags = []
features = []
min_version = "0.26"

[author]
  name = "Alexandre Segura"
